import pgpool-II-4.0.0.tar.gz

diff --git a/pgpool-II/src/tools/pgpool_setup b/pgpool-II/src/tools/pgpool_setup
--- a/pgpool-II/src/tools/pgpool_setup
+++ b/pgpool-II/src/tools/pgpool_setup
@@ -17,7 +17,7 @@
 # directory for *testing* purpose.
 # Do not use this tool for production environment!
 #
-# usage: pgpool_setup [-m r|s|n|l][-n num_clusters][-p base_port][-pg pg_base_port][--no-stop][-d]
+# usage: pgpool_setup [-m r|s|n|l][-n num_clusters][-p base_port][-pg pg_base_port][--no-stop][-d][-s][-r]
 # -m s: create an installation as streaming replication mode.
 # (the default)
 # -m r: create an installation as native replication mode.
@@ -34,6 +34,8 @@
 # pg_base_port + 1 and so on.
 # --no-stop: do not stop pgpool and PostgreSQL after the work
 # -d: start pgpool with debug mode
+# -s: use replication slot, rather than wal archive.
+# -r: use pg_rewind for base backup if possible.
 #
 # The user run this script will become the PostgreSQL super user as
 # well.  Current directory must be empty.  Assume that appropreate
@@ -73,7 +75,12 @@ LPATH=${PGLIB:-"/usr/local/pgsql/lib"}
 # unix socket directory
 PGSOCKET_DIR=${PGSOCKET_DIR:-"/tmp"}
 # initdb args
-INITDBARG="--no-locale -E UTF_8"
+INITDBARG="--no-locale -E UTF_8 --data-checksums"
+# Use replication slot
+USE_REPLICATION_SLOT=${USE_REPLICATION_SLOT:-"false"}
+# Use pg_rewind
+USE_PG_REWIND=${USE_PG_REWIND:-"false"}
+
 #-------------------------------------------
 # End of configuration section
 #-------------------------------------------
@@ -88,6 +95,10 @@ BASEDIR=`pwd`
 INITDB=$PGBIN/initdb
 PG_CTL=$PGBIN/pg_ctl
 PSQL=$PGBIN/psql
+
+# get PostgreSQL major version
+PGVERSION=`$INITDB -V|awk '{print $3}'|sed 's/\..*//'|sed 's/\([0-9]*\)[a-zA-Z].*/\1/'`
+echo PostgreSQL major version: $PGVERSION
 
 # pgpool-II configuration file localtion.
 CONF=$BASEDIR/etc/pgpool.conf
@@ -147,6 +158,7 @@ if [ a"$failed_node_id" = a"$old_primary_node_id" ];then	# master failed
 ! 	new_primary_db_cluster=${mydir}/data"$new_master_id"
 	echo $pg_ctl -D $new_primary_db_cluster promote >>$log	# let standby take over
 	$pg_ctl -D $new_primary_db_cluster promote >>$log	# let standby take over
+	sleep 2
 fi
 EOF
 
@@ -269,6 +281,7 @@ chmod 755 $1/$PGPOOL_REMOTE_START_SCRIPT
 function set_postgresql_conf
 {
 	PGCONF=$1/postgresql.conf
+	PGHBACONF=$1/pg_hba.conf
 
 	echo "listen_addresses = '*'" >> $PGCONF
 	echo "port = $PORT" >> $PGCONF
@@ -284,8 +297,14 @@ function set_postgresql_conf
 		echo "hot_standby = on" >> $PGCONF
 		echo "wal_level = hot_standby" >> $PGCONF
 		echo "max_wal_senders = $NUMCLUSTERS" >> $PGCONF
-		echo "archive_mode = on" >> $PGCONF
-		echo "archive_command = 'cp %p $BASEDIR/archivedir/%f </dev/null'" >> $PGCONF
+
+		if [ $USE_REPLICATION_SLOT = "false" ];then
+		    echo "archive_mode = on" >> $PGCONF
+		    echo "archive_command = 'cp %p $BASEDIR/archivedir/%f </dev/null'" >> $PGCONF
+		else
+		    num_slots=`expr $NUMCLUSTERS + 10`
+		    echo "max_replication_slots = $num_slots" >> $PGCONF
+		fi
 	elif [ $MODE = 'r' -o $MODE = 'l' -o $MODE = 'y' ];then
 		echo "wal_level = archive" >> $PGCONF
 		echo "archive_mode = on" >> $PGCONF
@@ -295,25 +314,44 @@ function set_postgresql_conf
 		fi
 	fi
 
-	ed $1/pg_hba.conf <<EOF
+    sed -i '/host.*all.*all.*trust$/s/^/#/g' $PGHBACONF
+    sed -i '/local.*all.*all.*trust$/s/^/#/g' $PGHBACONF
+
+    if [ $PGVERSION -gt 9 ];
+    then
+	echo "host      all   scram_user     0/0    scram-sha-256" >> $PGHBACONF
+	echo "host      all   md5_user       0/0    md5" >> $PGHBACONF
+    fi
+
+    echo "host      all   all       0/0    trust" >> $PGHBACONF
+
+    if [ $PGVERSION -gt 9 ];
+    then
+	echo "local      all   scram_user      scram-sha-256" >> $PGHBACONF
+	echo "local      all   md5_user        md5" >> $PGHBACONF
+    fi
+
+    echo "local      all   all      trust" >> $PGHBACONF
+
+    ed $1/pg_hba.conf <<EOF
 /^#local *replication/s/^#//p
 /^#host *replication/s/^#//p
 /^#host *replication/s/^#//p
 w
 q
 EOF
-
 }
 
 #-------------------------------------------
 # create basebackup.sh for streaming replication mode
-# argument: PostgreSQL database cluster directory
+# argument1: PostgreSQL database cluster
 #-------------------------------------------
 function create_basebackup_stream {
 SCRIPT=basebackup.sh
 cat >> $1/$SCRIPT <<'EOF'
 #! /bin/sh
 psql=__PGBIN__/psql
+pg_rewind=__PGBIN__/pg_rewind
 DATADIR_BASE=__DATADIR_BASE__
 PGSUPERUSER=__PGSUPERUSER__
 
@@ -321,12 +359,43 @@ master_db_cluster=$1
 recovery_node_host_name=$2
 DEST_CLUSTER=$3
 PORT=$4
+recovery_node=$5
+
+pg_rewind_failed="true"
 
 log=$DATADIR_BASE/log/recovery.log
+echo >> $log
+date >> $log
+EOF
+
+pg_rewind_failed="true"
+
+if [ $USE_PG_REWIND = "true" ];then
+cat >> $1/$SCRIPT <<'EOF'    
+
+# First try pg_rewind
+
+# Make backup copy of postgresql.conf since pg_rewind blindly copies
+# $master_db_cluster/postgresql.conf.
+cp $DEST_CLUSTER/postgresql.conf /tmp/
+echo "pg_rewind starts" >> $log
+$pg_rewind -P -D $DEST_CLUSTER --source-server="port=$PORT user=$PGSUPERUSER dbname=postgres" >> $log 2>&1
+if [ $? != 0 ];then
+    # pg_rewind failed. Fallback to rsync.
+   echo "pg_rewind failed. Fall back to rsync" >> $log
+   pg_rewind_failed="true"
+else
+   pg_rewind_failed="false"
+fi
+EOF
+fi
+
+cat >> $1/$SCRIPT <<'EOF'
+if [ $pg_rewind_failed = "true" ];then
 
 $psql -p $PORT -c "SELECT pg_start_backup('Streaming Replication', true)" postgres
 
-echo "source: $master_db_cluster dest: $DEST_CLUSTER" > $log
+echo "source: $master_db_cluster dest: $DEST_CLUSTER" >> $log
 
 rsync -C -a -c --delete --exclude postgresql.conf --exclude postmaster.pid \
 --exclude postmaster.opts --exclude pg_log \
@@ -338,14 +407,42 @@ rm -fr $DEST_CLUSTER/pg_xlog
 mkdir $DEST_CLUSTER/pg_xlog
 chmod 700 $DEST_CLUSTER/pg_xlog
 rm $DEST_CLUSTER/recovery.done
+fi
+EOF
+
+if [ $USE_REPLICATION_SLOT = "true" ];then
+    cat >> $1/$SCRIPT <<'EOF'
+$psql -p $PORT -c "SELECT * FROM pg_create_physical_replication_slot('pgpool_setup_slot$recovery_node')" postgres
+EOF
+fi
+
+cat >> $1/$SCRIPT <<'EOF'
 cat > $DEST_CLUSTER/recovery.conf <<REOF
 standby_mode          = 'on'
 primary_conninfo      = 'port=$PORT user=$PGSUPERUSER'
 recovery_target_timeline='latest'
+EOF
+
+if [ $USE_REPLICATION_SLOT = "false" ];then
+    cat >> $1/$SCRIPT <<'EOF'
 restore_command = 'cp $DATADIR_BASE/archivedir/%f "%p" 2> /dev/null'
 REOF
+EOF
+else
+    cat >> $1/$SCRIPT << 'EOF'
+primary_slot_name = 'pgpool_setup_slot$recovery_node'
+REOF
+EOF
+fi
 
+cat >> $1/$SCRIPT <<'EOF'
+if [ $pg_rewind_failed = "true" ];then
 $psql -p $PORT -c "SELECT pg_stop_backup()" postgres
+fi
+
+if [ $pg_rewind_failed = "false" ];then
+    cp /tmp/postgresql.conf $DEST_CLUSTER/
+fi
 EOF
 
 #-------------------------------------------
@@ -459,7 +556,7 @@ chmod 755 $1/$SCRIPT
 #-------------------------------------------
 # create initial recovery.conf
 # argument1: PostgreSQL database cluster directory
-# argument2: cluster No. we assume that data0 is primary
+# argument2: cluster No. We assume that data0 is primary
 #-------------------------------------------
 function create_recovery_conf {
 if [ $2 = "0" ];then
@@ -472,8 +569,34 @@ cat > $1/$fname <<EOF
 standby_mode          = 'on'
 primary_conninfo      = 'port=$BASEPORT user=$WHOAMI'
 recovery_target_timeline='latest'
+EOF
+if [ $USE_REPLICATION_SLOT = true ];then
+    echo "primary_slot_name = 'pgpool_setup_slot$2'" >> $1/$fname
+else
+cat >> $1/$fname <<EOF
 restore_command = 'cp $BASEDIR/archivedir/%f "%p" 2> /dev/null'
 EOF
+fi
+}
+
+function set_pool_hba_conf {
+    POOL_HBACONF=$1
+    sed -i '/host.*all.*all.*trust$/s/^/#/g' $POOL_HBACONF
+    sed -i '/local.*all.*all.*trust$/s/^/#/g' $POOL_HBACONF
+
+    if [ $PGVERSION -gt 9 ];
+    then
+	echo "host    all         scram_user  0/0                   scram-sha-256" >> $POOL_HBACONF
+	echo "host    all         md5_user    0/0                   md5" >> $POOL_HBACONF
+
+	echo "local   all         scram_user                        scram-sha-256" >> $POOL_HBACONF
+	echo "local   all         md5_user                          md5" >> $POOL_HBACONF
+    fi
+
+    echo "local   all         all                               trust" >> $POOL_HBACONF
+
+    echo "host    all         all         127.0.0.1/32          trust" >> $POOL_HBACONF
+    echo "host    all         all         ::1/128               trust" >> $POOL_HBACONF
 }
 
 #-------------------------------------------
@@ -559,12 +682,12 @@ function wait_for_pgpool_reload {
 ################################################################################
 function usage()
 {
-	echo "usage: $0 [-m r|s|n|l|y] [-n num_clusters] [-p base_port] [-pg pg_base_port][--no-stop] [-d]";exit 1
+	echo "usage: $0 [-m r|s|n|l|y] [-n num_clusters] [-p base_port] [-pg pg_base_port][--no-stop] [-d] [-s] [-r]";exit 1
 }
 
 #-------------------------------------------
 # Argument check
-# usage: $0  [-m r|s|n][-n num_clusters][-p base_port][-pg pg_base_port][--no-stop][-d]
+# usage: $0  [-m r|s|n][-n num_clusters][-p base_port][-pg pg_base_port][--no-stop][-d][-s][-r]
 #-------------------------------------------
 #
 # default mode is streaming replication mode
@@ -597,7 +720,10 @@ do
 		NO_STOP="true"
 	elif [ $1 = "-d" ];then
 		PGPOOLDEBUG="true"
-		shift;
+	elif [ $1 = "-s" ];then
+	    USE_REPLICATION_SLOT="true"
+	elif [ $1 = "-r" ];then
+	    USE_PG_REWIND="true"
 	elif [ $1 = "--help" -o $1 = "-o" ];then
 		usage
 		exit
@@ -626,6 +752,16 @@ case $MODE in
 	    ;;
 esac
 
+# If USE_REPLICATION_SLOT is provided as an environment variable, turn on -s
+if [ a$USE_REPLICATION_SLOT = a"true" ];then
+    USE_REPLICATION_SLOT="true"
+fi
+
+# If USE_PG_REWIND is provided as an environment variable, turn on -r
+if [ a$USE_PG_REWIND = a"true" ];then
+    USE_PG_REWIND="true"
+fi
+
 #-------------------------------------------
 # Make sure that current directory is empty
 #-------------------------------------------
@@ -640,7 +776,7 @@ exec 5> $BASEDIR/pgpool_setup.log
 #-------------------------------------------
 # everything looks good. starting setup...
 #-------------------------------------------
-echo "Satrting set up in $MODENAME"
+echo "Starting set up in $MODENAME"
 
 #-------------------------------------------
 # assign base port for PostgreSQL
@@ -653,6 +789,7 @@ BASEPORT=$PGBASEPORT
 #-------------------------------------------
 test ! -d etc && mkdir etc
 cp $SAMPLE_CONF $CONF
+cp $PGPOOLDIR/pool_hba.conf.sample $BASEDIR/etc/pool_hba.conf
 
 #-------------------------------------------
 # create startall, shutdownall and pgpool_reload
@@ -702,7 +839,7 @@ do
 	echo "creating basebackup.sh"
 	# create basebackup.sh
 	if [ $MODE = 's' ];then
-		create_basebackup_stream $CLUSTERDIR >&5 2>&1
+		create_basebackup_stream $CLUSTERDIR $n >&5 2>&1
 	elif [ $MODE = 'r' ];then
 		create_basebackup_replication $CLUSTERDIR >&5 2>&1
 		create_pgpool_recovery_pitr $CLUSTERDIR >&5 2>&1
@@ -725,6 +862,7 @@ do
 done
 
 set_pgpool_conf $CONF
+set_pool_hba_conf $BASEDIR/etc/pool_hba.conf
 
 PGPOOL_PORT=$ORIG_BASEPORT
 echo "port = $PGPOOL_PORT" >> $CONF
@@ -759,8 +897,10 @@ $PGPOOL_INSTALL_DIR/bin/pg_md5 $WHOAMI >> etc/pcp.conf
 # create pool_passwd
 $PGPOOL_INSTALL_DIR/bin/pg_md5 -m -f etc/pgpool.conf -u $WHOAMI $WHOAMI
 
-# create archive directory
-mkdir archivedir
+if [ $USE_REPLICATION_SLOT = "false" ];then
+    # create archive directory
+    mkdir archivedir
+fi
 
 #-------------------------------------------
 # if streaming replication mode, we need to create data1 and so on, by
@@ -776,6 +916,14 @@ CREATE EXTENSION pgpool_regclass;
 CREATE EXTENSION pgpool_recovery;
 CREATE DATABASE test;
 EOF
+	if [ $USE_REPLICATION_SLOT = "true" ];then
+	    n=0
+	    while [ $n -lt $NUMCLUSTERS ]
+	    do
+		$PSQL -p $BASEPORT template1 -c "SELECT * FROM pg_create_physical_replication_slot('pgpool_setup_slot$n')" >&5 2>&1
+		n=`expr $n + 1`
+	    done
+	fi
 
 	n=0
 	PORT=$BASEPORT
